### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by cielavenir**

### CODE REVIEW

**Comment by cielavenir** [comment]
Is Windows liblzma broken? Actually I see "the number of error: 1" also in my x64 computer.

**Comment by bicycle1885** [comment]
Have you built your liblzma from the source code?

**Comment by cielavenir** [comment]
liblzma is from WinRPM

**Comment by cielavenir** [comment]
This person says liblzma 5.0.5 fixes the error=5 issue (WinRPM's liblzma version is still 5.0.4).
http://einguste.hatenablog.com/entry/2013/03/20/233233
Perhaps we should keep this aside for a while...

**Comment by cielavenir** [comment]
(today I checked the official liblzma 5.2.3 with modern.ie Win10, but the error=5 wasn't cleared. that may be because the VM has 4GB memory, but...)

**Comment by bicycle1885** [comment]
I have no clue. Perhaps we should wait for the upstream fix or we need a Windows expert.

**Comment by bicycle1885** [comment]
Superseded by #8.

**Pull request closed without merging**
